//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"
#import "UNUserNotificationCenterDelegate.h"
#import "WXApiDelegate.h"

@class AVAudioPlayer, HTTPServer, NSString, UIWindow;

@interface AppDelegate : UIResponder <UNUserNotificationCenterDelegate, WXApiDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
    HTTPServer *_localHttpServer;
    NSString *_port;
    AVAudioPlayer *_audioPlayer;
}

@property(retain, nonatomic) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(copy, nonatomic) NSString *port; // @synthesize port=_port;
@property(retain, nonatomic) HTTPServer *localHttpServer; // @synthesize localHttpServer=_localHttpServer;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)handleUdid:(id)arg1;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)requestAuthor;
- (_Bool)copyMissingFile:(id)arg1 toPath:(id)arg2;
- (void)playBackground;
- (void)setLog;
- (void)startServer;
- (void)configLocalHttpServer:(long long)arg1;
- (void)initSever:(long long)arg1;
- (void)onResp:(id)arg1;
- (void)onReq:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

