//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CLLocationManagerDelegate.h"
#import "WKNavigationDelegate.h"
#import "WXApiDelegate.h"

@class CLLocationManager, NSString, UIButton, WKWebView;

@interface MainViewController : UIViewController <WKNavigationDelegate, CLLocationManagerDelegate, WXApiDelegate>
{
    _Bool _loadHttpSuc;
    WKWebView *_webView;
    NSString *_urlStr;
    CLLocationManager *_locationManager;
    NSString *_strLatitude;
    NSString *_strLongitude;
    UIButton *_wechatBtn;
}

@property(retain, nonatomic) UIButton *wechatBtn; // @synthesize wechatBtn=_wechatBtn;
/Users/luck/Desktop/github/BeePlayTestDemo/Pods@property(copy, nonatomic) NSString *strLongitude; // @synthesize strLongitude=_strLongitude;
@property(copy, nonatomic) NSString *strLatitude; // @synthesize strLatitude=_strLatitude;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) _Bool loadHttpSuc; // @synthesize loadHttpSuc=_loadHttpSuc;
@property(copy, nonatomic) NSString *urlStr; // @synthesize urlStr=_urlStr;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)postRequest;
- (void)sendAuthRequest;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locatemap;
- (void)commonWriteToServer;
- (void)openLocalcationSet;
- (void)openBeePlayDomaim;
- (void)changeEnvirment;
- (void)writeData:(id)arg1;
- (void)addHomeView;
- (void)HideBindBtn;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

