//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HTTPConnection.h"

@class MultipartFormDataParser, NSFileHandle, NSMutableArray;

@interface MyHttpConnection : HTTPConnection
{
    MultipartFormDataParser *parser;
    NSFileHandle *storeFile;
    NSMutableArray *uploadedFiles;
    NSMutableArray *_appArray;
}

@property(retain, nonatomic) NSMutableArray *appArray; // @synthesize appArray=_appArray;
- (void).cxx_destruct;
- (id)getSign;
- (void)getAPPList;
- (id)GetLogNowTime;
- (void)processBodyData:(id)arg1;
- (void)prepareForBodyWithSize:(unsigned long long)arg1;
- (id)httpResponseForMethod:(id)arg1 URI:(id)arg2;
- (_Bool)expectsRequestBodyFromMethod:(id)arg1 atPath:(id)arg2;
- (_Bool)supportsMethod:(id)arg1 atPath:(id)arg2;

@end

