//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPSessionManager, NSString;

@interface MyRequestManager : NSObject
{
    _Bool _isProduct;
    AFHTTPSessionManager *_manager;
    NSString *_serverHost;
}

+ (id)shareInstance;
@property(nonatomic) _Bool isProduct; // @synthesize isProduct=_isProduct;
@property(retain, nonatomic) NSString *serverHost; // @synthesize serverHost=_serverHost;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)requestWeixinAuthOpenId:(id)arg1;
- (void)requestWeixinAuthToken:(id)arg1;
- (void)requestWeixinBind:(id)arg1;
- (void)requestLoginDevelop:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestLoginProduction:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)initServer;

@end

