//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MySystemManager : NSObject
{
    NSString *_latitude;
    NSString *_longitude;
    NSString *_sessionid;
    NSString *_userid;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSString *userid; // @synthesize userid=_userid;
@property(retain, nonatomic) NSString *sessionid; // @synthesize sessionid=_sessionid;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
- (void).cxx_destruct;
- (void)initData;

@end

