//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Tools : NSObject
{
}

+ (id)getSixNumberRandom;
+ (void)openLocationSetting;
+ (_Bool)openWithBundleId:(id)arg1;
+ (id)makeSignSort:(id)arg1;
+ (id)makeParamsSort:(id)arg1;
+ (id)md5:(id)arg1;
+ (id)currentTimeStr;
+ (void)pasteWithStr:(id)arg1;
+ (id)getSignWithPara:(id)arg1;
+ (void)registerNotification:(long long)arg1;
+ (_Bool)isSIMInstalled;
+ (void)exitApplication;
+ (id)getUdid;
+ (id)getIpAddressCell;
+ (id)getIpAddressWIFI;
+ (id)ipAddressWithIfaName:(id)arg1;
+ (id)getDeviceIPAddresses;
+ (id)getMacAddress;
+ (id)getDevicePlatform;
+ (_Bool)isJailBreakWay4;
+ (_Bool)isJailBreakWay3;
+ (_Bool)isJailBreakWay2;
+ (_Bool)isJailBreakWay1;
+ (_Bool)isJailBreak;
- (void)exitAPP;

@end

