//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZIKCellularAuthorization : NSObject
{
}

+ (void)setAppFixed:(_Bool)arg1;
+ (_Bool)appFixed;
+ (_Bool)isDeviceChineseLanguage;
+ (_Bool)deviceNeedFix;
+ (void)requestFinish;
+ (void)requestCellularAuthorization;

@end

